### ISSUE TITLE
[EPIC] Renovation of the Doc Site and Home Page

### ISSUE THREAD

**Issue by MrCoder** [ZenUml/docs#1]
- [x] 生成网站并提交到docs代码库
- [x] 创建GitHub Actions构建静态网站和部署到Cloudflare Pages
- [x] 创建首页，并部署到Cloudflare Pages
- [x] 修改DNS记录将https://zenuml.com指向新首页
- [ ] 迁移和创建文档站内容
- [ ] 修改DNS Record，将https://docs.zenuml.com重定向到https://zenuml.com/docs
- [ ] 配置SEO

**Comment by MrCoder** [comment]
文档页（非首页）是否应当支持评论？评论可以用GitHub Discussions实现：https://m19v.github.io/blog/how-to-add-giscus-to-docusaurus

**Comment by dyon21** [comment]
> 文档页（非首页）是否应当支持评论？评论可以用GitHub Discussions实现：https://m19v.github.io/blog/how-to-add-giscus-to-docusaurus

文档页面感觉不太适合加评论？用户有疑问可以到 Issues 提，然后我们再补充到文档中，如果后面会写 blog 的话 blog 页可以加

**Comment by MrCoder** [comment]
https://www.uml-diagrams.org/sequence-diagrams.html 这是一个文档页面加评论的例子（往下翻）

**Comment by MrCoder** [comment]
https://chrome.google.com/webstore/detail/website-seo-checker-free/nljcdkjpjnhlilgepggmmagnmebhadnk/related 用这个工具简单的测一下SEO。

**Comment by MrCoder** [comment]
Tasks have been created for remaining items. Closing this one.
